monitor:
  directories:
    - "/Users/admin/Projects/file-monitor"
  ignore:
    files:
      - "*.tmp"
      - "*.log"
    extensions:
      - ".bak"
      - ".swp"
      - ".DS_Store"
      - ".xls"
      - ".xlsx"
      - ".doc"
      - ".docx"
      - ".ppt"
      - ".pptx"
      - ".pdf"
      - ".zip"
      - ".rar"
      - ".7z"
      - ".tar"
      - ".gz"
      - ".bz2"
      - ".jpg"
      - ".jpeg"
      - ".png"
      - ".gif"
    directories:
      - "/Users/admin/Projects/file-monitor/logs"
  events:
    - create
    - write
    # - delete

webhook:
  enabled: false
  provider: "serverchan"
  sendkey: "your_sendkey_here"
  template: "default"

email:
  enabled: false
  smtpHost: "smtp.example.com"
  smtpPort: 587
  username: "your_email@example.com"
  password: "your_app_password"
  from: "noreply@example.com"
  to:
    - "admin@example.com"
    - "backup@example.com"

logging:
  file: "/Users/admin/Projects/file-monitor/logs/monitor.log"
  maxSize: 10 # MB
  maxBackups: 5
  maxAge: 90 # days
  compress: true
